[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor Settings
monitor_speed = 115200
monitor_filters = time, default

; Library Dependencies
lib_deps =
    pierremolinaro/ACAN2517FD @ ^2.1.11

build_flags =
    -D CORE_DEBUG_LEVEL=3
